"""Tests for core/log_parser.py."""

from core.log_parser import parse_log, summarize

# Re-echoed lines use 6 leading spaces so ECHO_LINE_RE (^\s{0,6}) matches them
# in the lookahead. The macro NOTE follows the third ERROR so the lookahead
# can set is_macro_generated before the backward-scan fallback runs.
SAMPLE_LOG = """NOTE: Copyright (c) 2002-2012 by SAS Institute Inc.

1    /* Clean Salaries */
2    data work.salaries_clean;
3        set work.employees;
4        salary_new = salry * 1.1;
5        if age > 65 then retirement_flag = 1;
6        else retirement_flag = 0;
7    run;

ERROR: Variable SALRY not found in data set WORK.EMPLOYEES.
NOTE: The SAS System stopped processing this step because of errors.
      4         salary_new = salry * 1.1;

WARNING: The data set WORK.SALARIES_CLEAN may be incomplete.

8    proc means data=work.salaries_clean;
9        var salary_new;
10       classs department;
11   run;

ERROR: Statement is not valid or it is used out of proper order.
      10        classs department;

12   %some_macro();

ERROR: Macro variable REPTYPE has not been resolved.
NOTE: Line generated by the macro REPORTMAC.
"""

# Built once at module load; shared by all tests.
parsed = parse_log(SAMPLE_LOG)


def test_echoed_lines_built() -> None:
    assert set(range(1, 13)).issubset(parsed.echoed_lines.keys())
    assert "salary_new" in parsed.echoed_lines[4]


def test_error_count() -> None:
    assert len(parsed.errors) == 3


def test_warning_count() -> None:
    assert len(parsed.warnings) == 1


def test_first_error_message() -> None:
    msg = parsed.errors[0].message
    assert "SALRY" in msg
    assert not msg.startswith("ERROR")


def test_first_error_line_number() -> None:
    assert parsed.errors[0].log_line_number == 4


def test_first_error_echoed_source() -> None:
    src = parsed.errors[0].echoed_source_line
    assert src is not None
    assert "salry" in src.lower()


def test_second_error_line_number() -> None:
    assert parsed.errors[1].log_line_number == 10


def test_macro_flag() -> None:
    assert parsed.errors[2].is_macro_generated is True


def test_warning_severity() -> None:
    assert parsed.warnings[0].severity == "WARNING"


def test_summarize_output() -> None:
    summary = summarize(parsed)
    assert "3 error(s)" in summary
    assert "1 warning(s)" in summary


def test_empty_log() -> None:
    result = parse_log("")
    assert result.entries == []
    assert result.echoed_lines == {}


def test_no_errors_log() -> None:
    notes_only = "NOTE: First note.\nNOTE: Second note.\nNOTE: Third note.\n"
    result = parse_log(notes_only)
    assert result.errors == []
    assert result.warnings == []
