"""Parses a SAS .log file and returns a list of structured SASError dataclass records."""

import logging
import re
from dataclasses import dataclass

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module-level regex constants
# ---------------------------------------------------------------------------

# SAS-echoed source lines: optional leading indent (0-6 spaces), line number, 1+ spaces, code text
# Example: "    3    set work.employees;" or "4        salary_new = salry * 1.1;"
ECHO_LINE_RE = re.compile(r"^\s{0,6}(\d+)\s{1,5}(.+)$")

# SAS re-echo lines printed after an error: 7+ leading spaces, line number, 1+ spaces, non-space start
# Example: "       4          salary_new = salry * 1.1;"
# Requiring a non-space char after the spaces prevents matching bare error codes ("22", "76").
REECHO_LINE_RE = re.compile(r"^\s{7,}(\d+)\s{1,}(\S.*)")

# Opening line of an ERROR or WARNING entry (column 0, colon or space follows keyword)
SEVERITY_RE = re.compile(r"^(ERROR|WARNING)[:\s]")

# Continuation lines: 7+ leading spaces, not starting a new ERROR/WARNING keyword
CONTINUATION_RE = re.compile(r"^\s{7,}(?!ERROR|WARNING)")

# SAS note emitted when an error originates inside a macro expansion
MACRO_NOTE_RE = re.compile(r"^NOTE:\s+Line generated by", re.IGNORECASE)

# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class SASError:
    severity: str  # "ERROR" or "WARNING"
    message: str  # full error text, may span multiple lines
    log_line_number: int | None  # SAS source line number referenced in the echoed code
    echoed_source_line: str | None  # the SAS code line SAS printed in the log
    is_macro_generated: bool  # True if the error came from a macro expansion
    raw_block: str  # raw text block surrounding this error


@dataclass
class ParsedLog:
    entries: list[SASError]
    echoed_lines: dict[int, str]  # line_number -> code text, built from SAS echo
    raw_text: str

    @property
    def errors(self) -> list[SASError]:
        return [e for e in self.entries if e.severity == "ERROR"]

    @property
    def warnings(self) -> list[SASError]:
        return [e for e in self.entries if e.severity == "WARNING"]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def parse_log(log_text: str) -> ParsedLog:
    """Parse raw SAS log text into a structured ParsedLog.

    Two-pass algorithm:
      Pass 1 — build echoed_lines dict from SAS-echoed source lines.
      Pass 2 — walk forward collecting ERROR/WARNING blocks with context.
    """
    lines = log_text.splitlines()

    # ------------------------------------------------------------------
    # Pass 1: build echoed_lines {line_number: code_text}
    # ------------------------------------------------------------------
    echoed_lines: dict[int, str] = {}
    for line in lines:
        m = ECHO_LINE_RE.match(line)
        if m:
            echoed_lines[int(m.group(1))] = m.group(2)
        else:
            m2 = REECHO_LINE_RE.match(line)
            if m2:
                # setdefault: original source echo takes priority over re-echo
                echoed_lines.setdefault(int(m2.group(1)), m2.group(2))

    logger.debug("Pass 1 complete: %d echoed source lines indexed", len(echoed_lines))

    # ------------------------------------------------------------------
    # Pass 2: extract ERROR / WARNING blocks
    # ------------------------------------------------------------------
    entries: list[SASError] = []
    i = 0
    while i < len(lines):
        sev_match = SEVERITY_RE.match(lines[i])
        if not sev_match:
            i += 1
            continue

        severity: str = sev_match.group(1)
        block_start = i

        # Collect message: strip severity keyword from the opening line, then
        # append indented continuation lines. Stop at echo lines.
        first_line_text = lines[i][len(severity) :].lstrip(": ").strip()
        message_parts: list[str] = [first_line_text]
        j = i + 1
        while j < len(lines):
            cont_line = lines[j]
            if CONTINUATION_RE.match(cont_line) and not ECHO_LINE_RE.match(cont_line) and not REECHO_LINE_RE.match(cont_line):
                message_parts.append(cont_line)
                j += 1
            else:
                break

        message = "\n".join(message_parts)

        # Lookahead: scan from block_start through 10 lines past the message.
        # Starting at block_start catches re-echo lines that SAS prints inside
        # the error block (before or after the message text).
        lookahead_end = j + 10
        is_macro_generated = False
        log_line_number: int | None = None
        echoed_source_line: str | None = None
        lookahead_seen: set[int] = set()

        for k in range(block_start, min(lookahead_end, len(lines))):
            if MACRO_NOTE_RE.match(lines[k]):
                is_macro_generated = True
            if log_line_number is None:
                m = ECHO_LINE_RE.match(lines[k])
                if not m:
                    m = REECHO_LINE_RE.match(lines[k])
                if m:
                    candidate = int(m.group(1))
                    lookahead_seen.add(candidate)
                    if candidate in echoed_lines:
                        log_line_number = candidate
                        echoed_source_line = echoed_lines[candidate]

        # Fallback: scan backward up to 30 lines for nearest echoed source line.
        # Only accept a candidate within 5 of any line number seen in the lookahead
        # to avoid picking up an echo from a previous unrelated code block.
        if log_line_number is None:
            scan_start = max(0, block_start - 30)
            for k in range(block_start - 1, scan_start - 1, -1):
                m = ECHO_LINE_RE.match(lines[k])
                if not m:
                    m = REECHO_LINE_RE.match(lines[k])
                if m:
                    candidate = int(m.group(1))
                    if candidate in echoed_lines:
                        if not lookahead_seen or any(
                            abs(candidate - n) <= 5 for n in lookahead_seen
                        ):
                            log_line_number = candidate
                            echoed_source_line = echoed_lines[candidate]
                            break

        raw_block = "\n".join(lines[block_start : min(lookahead_end, len(lines))])

        entries.append(
            SASError(
                severity=severity,
                message=message,
                log_line_number=log_line_number,
                echoed_source_line=echoed_source_line,
                is_macro_generated=is_macro_generated,
                raw_block=raw_block,
            )
        )

        logger.debug(
            "Found %s at block line %d (source line %s)",
            severity,
            block_start,
            log_line_number,
        )

        i = j  # advance past the collected message block

    logger.info(
        "parse_log complete: %d error(s), %d warning(s)",
        sum(1 for e in entries if e.severity == "ERROR"),
        sum(1 for e in entries if e.severity == "WARNING"),
    )

    return ParsedLog(entries=entries, echoed_lines=echoed_lines, raw_text=log_text)


def summarize(parsed: ParsedLog) -> str:
    """Return a human-readable summary of a ParsedLog."""
    header = (
        f"Parsed log: {len(parsed.errors)} error(s), {len(parsed.warnings)} warning(s)"
    )
    parts: list[str] = [header, ""]

    for entry in parsed.entries:
        line_ref = (
            f"line {entry.log_line_number}"
            if entry.log_line_number is not None
            else "line unknown"
        )
        macro_tag = " [macro-generated]" if entry.is_macro_generated else ""
        parts.append(f"[{entry.severity}] {line_ref}{macro_tag}")
        parts.append(f"  Message: {entry.message.strip()}")
        if entry.echoed_source_line is not None:
            parts.append(f"  Source:  {entry.echoed_source_line.strip()}")
        parts.append("")

    return "\n".join(parts)
